### create or update card 

POST http://localhost:5000/api/cards HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjExNDEyYTgzNjUyNWMxNmE3ZWQxNGU2In0sImlhdCI6MTYyODcwNjU1NCwiZXhwIjoxNjI4NzQyNTU0fQ.r5DsElDtjTxoUmcrUqtHXreGcUukBO9cYmsKOvN8lrM
Content-Type: application/json

{
 "nameoncard": "Test Card",
 "cardnumber": "1234123412341234",
 "expiredate": "07/2024",
 "cvv": 321
}
