### Create a product 

POST http://localhost:5000/api/products HTTP/1.1
Content-Type: application/json

{
  "name": "Full Keyboard",
  "catagory": "Layout",
  "shortdesc": "Full 108 key keyboard",
  "longdesc": "add text here ",
  "photo": "",
  "price": 100.00
}


### Get all products

GET http://localhost:5000/api/products HTTP/1.1



### Get products by catagory

GET http://localhost:5000/api/products/switch HTTP/1.1
