### Create a product 

POST http://localhost:5000/api/products HTTP/1.1
Content-Type: application/json

{
  "name": "Red Switches",
  "catagory": "switch",
  "shortdesc": "smooth and quiet switches",
  "longdesc": " add more information here ",
  "photo": "",
  "price": 100.00
}


### Get all products

GET http://localhost:5000/api/products HTTP/1.1



### Get products by catagory

GET http://localhost:5000/api/products/switch HTTP/1.1
